matrix:
  include:
    - language: go
      go: 1.12.x
      before_script:
      - go mod install
      script:
      - go test ./...

    - language: node_js
      node_js: 10
      cache: npm 
      before_script:
      - npm install
      script:
      - ng test
      - ng build
    