language: go
go: 1.12.x
env:
- GO111MODULE=on
before_install:
- nvm install 10
- nvm use 10
install:
# go dependencies
- go mod download
# travis dependencies
- cd frontend
- npm install
- cd ..
script:
- go test ./...
- go build
- cd frontend
- npm run-script build