matrix:
  include:
    - language: go
      go: 1.12.x
      before_script:
      - go mod download
      script:
      - go test ./...

    - language: node_js
      node_js: 10
      cache: npm 
      before_script:
      - npm install
      - npm install -g @angular/cli
      script:
      - ng test
      - ng build
    