language: go
go: 1.12.x
env:
- GO111MODULE=on
before_install:
- nvm install 10
- nvm use 10
install:
- go mod download
- cd frontend
- npm install
- cd ..
script:
- go test ./...
- go build -o japare -v .
- cd frontend
- npm run-script build
deploy:
  provider: heroku
  api_key:
    secure: ReRfAGMDpO1xTnQKYvbpp0pMyItxo3ZdjPChIZi4vXEprqzh61cFC13eKk3nODdPZJHK9WwhFS2EF03yBrmsNqgB6GX83AC5+zCj/9XeGJStyEmZH7JDTd0gJlkR5s0ZLJDdLTBajavGKCamojdqifD975BIu/9GtrhMjBSFQ4nQMopBl8Z8XHQQ/e6kYJQEsEeEy3uvp9aUrXBSK5rJyK5WszqJOKrWA0wYWQCVfa/yO7W+M/7kO/mJ70aJ3aEBwt+BCbJ5phSjdrUCAqCyJ6EBmaet4U5caYWM/zrD512q6eiK+VDsk5DGxfqxGKv0850U9nEMeoDy0OrphMhCOsHLAx+z+/tiAgwznp7bDsyKCMJGwVLLfp2DerVKPMOpXwTvujYR1FTI9kDwVM9mBXmiqmw8t8SkolFRMXOsips5pCVE1SnLTxn70e9JpPqfEWABlfu5hktPZIff9sNtDuAxtUI0TZ1DX/YE3AKQ4AXjkpU3S0ejN/1OXfU79rpVAlGEsxAyvsInNOyZaikcjszd2xqr5pP2Dc6DX4/fGgCvF8nzISVirYUKz9dasCc73BQshfrkfMKqiTY3F7hXX51KIsZe03YnS7z3CMVBQNmyuDIsk1PIb+zJjt9rRGQXFRpo2MezdT7/156uxo7ZEsxl11486LU9jsRGJHVwvXY=
